[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200